root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/react
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
rules:
  '@typescript-eslint/no-empty-interface': off
  react/prop-types:
    - error
    - skipUndeclared: true
  react/self-closing-comp: error
  react/react-in-jsx-scope: off
  jsx-a11y/anchor-is-valid:
    - error
    - components: [Link]
